apiVersion: v1
kind: ReplicationController
metadata:
  name: kubernetes-training-controller
spec:
  replicas: 2
  selector:
    app: kubernetes-training
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: natashashafqat/kubernetes-training-demo
        ports:
        - name: nodejs-port
          containerPort: 3000