apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-training-pod
  labels:
    app: kubernetes-training
spec:
  containers:
    - name: k8s-demo
      image: natashashafqat/kubernetes-training-demo
      ports:
      - name: nodejs-port
        containerPort: 3000